# Generated by Django 5.2.3 on 2025-06-26 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, unique=True)),
                ('apellidos', models.CharField(max_length=100, unique=True)),
                ('ci', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=100, unique=True)), 
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        # Modelo Costo
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('monto', models.DecimalField(max_digits=10, decimal_places=2)),
            ],
        ),
        # Modelo Curso
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_horas', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
       # Modelo Inscripcion
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('costo', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='inscripcion.Costo')),
                ('curso', models.ForeignKey(on_delete=models.CASCADE, to='inscripcion.Curso')),
                ('estudiante', models.ForeignKey(on_delete=models.CASCADE, to='inscripcion.Estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
